### ISSUE TITLE
EnsureSeedData(): client.ToEntity() Exception!

### ISSUE THREAD

**Issue by roydcapella** [ChrisRichner/CoreWebApp.Quickstart#1]
Hi! I'm try with your code, but it has a error when loads the method **EnsureSeedData()** in startup.cs a line `**context.Clients.Add(client.ToEntity()):`**

This throws the exception: **System.TypeInitializationException' in IdentityServer4.EntityFramework.dll pero no se controló en el código del usuario Información adicional: The type initializer for 'IdentityServer4.EntityFramework.Mappers.ClientMappers' threw an exception.**

What could it be?

Thank you very much for sharing your efforts with the .Net community ... This code is serving me a lot to develop my application.

Thanks!!!

**Comment by ChrisRichner** [comment]
I've faced similar runtime issues as well during the development phase. Most of the time after updating nuget packages the code compiled but had runtime exceptions.

I've updated the nuget packages and fixed the runtime error.

You're welcome! Glad to know that my effort helps in kick start some one else.

**Comment by roydcapella** [comment]
Excellent my friend! I can run this starkit! Awesome! 

I updated all nugets packages, and all is well!

Thanks, Thanks, Thanks!
